# Nombre de la aplicacion
spring.application.name=producer_kafka

# Puerto del servidor web
server.port=8080

# Configuracion de conexion Kafka
spring.kafka.producer.bootstrap-servers=localhost:9092

# Habilitar todos los endpoints de Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Configuracion de logging
logging.level.com.backend.producer_kafka=INFO
