# Nombre de la aplicacion
spring.application.name=consumer_kafka

# Puerto del servidor web
server.port=8100

# Configuracion de conexion Kafka
spring.kafka.consumer.bootstrap-servers=localhost:9092

# Habilitar todos los endpoints de Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Configuracion de logging
logging.level.com.backend.consumer_kafka=INFO
